### PR TITLE
Feature/migrate allure2

### PR DESCRIPTION
**Pull request by Mjl33**
Migrate to allure 2

Allure lifecycles are:
mvn allure:serve  - generates a report, hosted on a temporary webserver for lifetime of 1 hour
mvn allure:report  - generates a report to directory target/site/allure-maven/index.html

=====
Breaking changes
Remove support for ru.yandex.qatools based annotations -> use io.qameta equivalent annotations instead
cucumberjvm screenshot mechanism to allure removed (to be implemented again)

### CODE REVIEW

**Comment by ham1** [comment]
I'd like to merge after updating to the latest Selenium which I will do in the next few weeks.

**Comment by ham1** [comment]
I've just rebased so it's easier to merge and review.

**Comment by ham1** [comment]
@Mjl33 quick qu, is there al `AllureLogger.stepStart(stepName)` and `endStep` alternative, or should people just refactor their code into methods with `@Step`?

**Comment by Mjl33** [comment]
@ham1 Allure2 has a fluent method of doing that
```
AllureLifecycle lifecycle = Allure.getLifecycle();
final String uuid = UUID.randomUUID().toString();
final StepResult result = new StepResult()
        .withName("Custom Step")
        .withParameters(Collections.singletonList(new Parameter().withName("parameter").withValue("hello")));
```
This would result in a "@Step" labeled "Custom Step" and sub-leaf showing parameter value of "hello"

**Pull request merged**
