### PR TITLE
Add Edge Support (formatting)

### PR DESCRIPTION
**Pull request by david-apples**

### CODE REVIEW

**Comment by ham1** [comment]
The checkstyle is failing:

```DriverSetup.java:111:9: '}' at column 9 should be on the same line as the next part of a multi-block statement (one that directly contains multiple blocks: if/else-if/else, do/while or try/catch/finally).```

See: https://travis-ci.org/Frameworkium/frameworkium-core/builds/412466224

**Comment by david-apples** [comment]
should we relax some of these checks : D...there are 20 forks of the project already so if people cannot get needed changes merged in a timely manner things will keep splintering into forks

**Comment by ham1** [comment]
I'm reluctant to do that as I think keeping consitant formatting is actually really important for readability and thus maintainability (it also annoys me more than maybe it should?). Also I think it relates to the [broken windows theory ](https://en.wikipedia.org/wiki/Broken_windows_theory) e.g. if you let a few things slide then others take less care and you get more broken windows etc.

**Comment by ham1** [comment]
If you import the formatter `doc/style/intellij-java-style.xml` into IntelliJ formatting, it can be project specific so it doesn't change your other projects, then just autoformat it should largely work and not cause checkstyle errors.

**Comment by ham1** [comment]
Please see #114

**Pull request closed without merging**
