### PR TITLE
Update jacoco coverage test script and reporting setup to support codeclimate

### PR DESCRIPTION
**Pull request by TheoOkafor**
This PR updates the jacoco coverage test script and reporting setup to support Codeclimate

REFERENCES:
- https://medium.com/capital-one-tech/improve-java-code-with-unit-tests-and-jacoco-b342643736ed
- https://github.com/TheoOkafor/mini-calendly-java (This is my personal repo where I have this setup working)

### CODE REVIEW

**Comment by ham1** [comment]
Hi, thank you for the PR.

Would you be able to describe the problem it solves?
I'm under the impression that our current setup works and reports the code coverage.
Should this PR replace some of the existing code as I only see additions not deletions?

**Comment by TheoOkafor** [comment]
Hi @ham1, 
The current setup is totally fine.

I had a challenge setting up code coverage reporting for codeclimate using jacoco. I followed a link from a Github issue to this project while looking for answers. I saw that your code-climate report wasn't working as well. I decided to share what I have done to got mine to work within this pull request, in case the team is still interested in getting coverage reporting through codeclimate.

I totally understand that this might not be a priority at the moment.

**Comment by ham1** [comment]
Ah, yes, thank you that makes sense. I think we will merge once we've fixed out build, but that might take a while due to lack of time :)

**Comment by TheoOkafor** [comment]
It's alright. I get it. You're welcome!

**Pull request closed without merging**
